---
  - name: Deploy/upgrade nethermind 
    hosts: netherminds
    become: yes
    become_user: root
    tasks:
      - name: Install packages 
        ansible.builtin.apt:
          pkg:
          - libsnappy-dev 
          - libc6-dev 
          - libc6 
          - unzip 
          - nginx

      - name: Create database directory
        file: 
          path: "{{ nethermind_location }}/db"
          state: directory
          mode: '0755'

      - name: transfer nethermind
        copy:
          src: "{{ nethermind_zip }}"
          dest: "/tmp/nethermind.zip"

      - name: Download and unarchive Nethermind
        ansible.builtin.unarchive:
          src: "/tmp/nethermind.zip"
          remote_src: yes
          dest: "{{ nethermind_location }}"

      - name: Clear out chainspec, Data, config
        shell: "rm -rf {{ nethermind_location }}/config && rm -rf {{ nethermind_location }}/Data"

      - name: Create Nethermind static-nodes
        template:
          src: "./chains/{{ use_chain }}/static-nodes.json"
          dest: "{{ nethermind_location}}/static-nodes.json"
  
      - name: Create Nethermind config 
        template:
          src: "./nethermind.cfg.j2"
          dest: "{{ nethermind_location }}/nethermind.cfg"

      - name: Create Nethermind chainspec.json 
        template:
          src: "./chains/{{ use_chain }}/chainspec.json"
          dest: "{{ nethermind_location }}/chainspec.json"
      
      - name: Create nethermind.service
        template:
          src: "./nethermind.service.j2"
          dest: "/etc/systemd/system/nethermind.service"

      - name: copy keyfile (maybe)
        copy: src="{{ sealer_keyfile }}" dest="{{ nethermind_location }}/keystore/"
        when: sealer_keyfile 

      - name: remove keyfile password
        when: sealer_keyfile 
        file: path="{{ nethermind_location}}/keystore/passwd" state=absent

      - name: deploy keyfile password
        when: sealer_keyfile 
        lineinfile:
          path: "{{ nethermind_location }}/keystore/passwd"
          line: "{{ sealer_keyfile_passwd }}"
          create: yes
          state: present

      - name: Set Nethermind ownership
        ansible.builtin.file:
          path: "{{ nethermind_location }}"
          state: directory
          mode: 0700
          owner: "{{ service_user }}"
          recurse: yes

      - name: Enable and start Nethermind
        systemd:
          name: nethermind.service
          daemon_reload: yes
          enabled: yes
          masked: no
          state: restarted

...


