---
  - name: Play 
    hosts: all
    become: yes
    become_user: root
    tasks:
      - name: Stop nethermind
        ansible.builtin.systemd:
          name: nethermind.service
          daemon_reload: yes
          enabled: no
          masked: no
          state: stopped

      - name: Clear out chainspec, Data, config
        shell: rm -rf {{ nethermind_location }}/config {{ nethermind_location }}/db {{ nethermind_location }}/plugins {{ nethermind_location }}/db/peers/SimpleFileDb.db {{ nethermind_location }}/db/SimpleFileDb.db


      - name: Clear database directory, plugs, logs, executables
        shell: 
          cmd: rm -rf db plugins logs Neth*
          chdir: "{{ nethermind_location }}"

...
