  - name: 
    hosts: all
    become: yes
    become_user: root
    tasks:
      - name: Stop Nethermind
        ansible.builtin.systemd:
          name: nethermind
          state: stopped

      - name: Rsync out Nethermind Database 
        ansible.builtin.command: rsync -av --progress /opt/nm/nethermind_db /mnt/nethermind_db

      - name: Restart Nethermind
        ansible.builtin.systemd:
          name: nethermind
          state: restarted
          daemon_reload: yes
